### ISSUE TITLE
As a single player, I need to know which guessed letters are in the word

### ISSUE THREAD

**Issue by benpalay** [witseie-elen4010/2022-group-lab-001#38] opened 2022-05-12 07:15 UTC

**Comment by IlanMalk** [comment] 2022-05-12 11:31
# Color codes

- Grey: letter not in word
- Yellow: 

TODO: add exact colour (hexidecimal value/identifier)


# Acceptance Tests
(For example, assuming correct word is ADIEU)

Happy cases:
- [ ] Enter a valid word that shares no letters with the correct word. Submit the guess. All the letters in the guessed word should go grey.
- [ ] Enter a valid word that shares some (but not all) letters with the correct word. The letters they have in common should go yellow and the others should go grey.
- [ ] Enter a valid word that contains a duplicate of a letter in the correct word (e.g. SEEDS). Check that *only one* of the Es goes yellow and that this is determined randomly. 


Sad cases: (*Check that none of the guessed word's letters change colour* in these cases)
- [ ] Enter a word _shorter than 5 letters_ and attempt to submit it.
- [ ] Enter a 5-letter word that is _not in the game's dictionary_.

**Closed** 2022-06-02 21:46 UTC
Labels: user story, 2
